POST http://localhost:3000/auth

###

GET http://localhost:3000/balance
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNvZGVfY2hhbGxlbmdlIiwiaWF0IjoxNjk5OTQyNTMxLCJleHAiOjE2OTk5NDI4MzF9.zl5tde1WozNm31AFgUdDZYtKlHthfhVBAsh-yo6N14Q

###

Post http://localhost:3000/withdraw
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNvZGVfY2hhbGxlbmdlIiwiaWF0IjoxNjk5OTQyNTMxLCJleHAiOjE2OTk5NDI4MzF9.zl5tde1WozNm31AFgUdDZYtKlHthfhVBAsh-yo6N14Q
content-type: application/json

{
    "amount": 75.0
}
###

Post http://localhost:3000/deposit
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNvZGVfY2hhbGxlbmdlIiwiaWF0IjoxNjk5OTQyNTMxLCJleHAiOjE2OTk5NDI4MzF9.zl5tde1WozNm31AFgUdDZYtKlHthfhVBAsh-yo6N14Q
content-type: application/json

{
    "amount": 55
}